
server:
  port: 9478

# Datasource
#############################
# Datasource setting
# Use jdbc connection
#############################
spring:
  datasource:
    driverclassName: org.mariadb.jdbc.Driver
    # url: jdbc:mariadb://maria:3306/deemo
    url: jdbc:mariadb://0.0.0.0:3306/deemo
    username: root
    password: 1qaz2wsx
    auto-commit: true
    idle-timeout: 30000
    pool-name: HikariCpExample
    max-lifetime: 1800000
    connection-timeout: 30000
    connection-test-query: SELECT 1
  jpa:
    show-sql: true