apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/ed/docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: adminer
  name: adminer
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8080
  selector:
    io.kompose.service: adminer
status:
  loadBalancer: {}
