apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/ed/docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: jenkins
  name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f /Users/ed/docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.network/default: "true"
        io.kompose.service: jenkins
    spec:
      containers:
      - image: jenkins/jenkins:lts
        imagePullPolicy: ""
        name: jenkins
        ports:
        - containerPort: 18080:8080
        - containerPort: 50000:50000
        resources: {}
        volumeMounts:
        - mountPath: /usr/local/maven
          name: jenkins-claim0
        - mountPath: /usr/local/jdk
          name: jenkins-claim1
        - mountPath: /var/jenkins_home
          name: data-share
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: jenkins-claim0
        persistentVolumeClaim:
          claimName: jenkins-claim0
      - name: jenkins-claim1
        persistentVolumeClaim:
          claimName: jenkins-claim1
      - name: data-share
        persistentVolumeClaim:
          claimName: data-share
status: {}
