apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /Users/ed/docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: lab-api
  name: lab-api
spec:
  ports:
  - name: "9478"
    port: 9478
    targetPort: 9478
  selector:
    io.kompose.service: lab-api
status:
  loadBalancer: {}
